spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/novel?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&AllowPublicKeyRetrieval=True
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
logging:
  config: classpath:log4j2.xml
